#########################################
##             Xpra Base               ##
#########################################

FROM ubuntu:22.04 as xpra-base

# Set default password
ENV XPRA_PASSWORD xpra

# Add winswitch repository and install Xpra
RUN set -ex \
    \
    && UBUNTU_VERSION=$(cat /etc/os-release | grep UBUNTU_CODENAME | sed 's/UBUNTU_CODENAME=//') \
    \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl \
        gnupg \
        openssl \
        python3-requests \
        python3-xdg \
    \
    && curl http://xpra.org/gpg.asc | apt-key add - \
    && echo "deb http://xpra.org/ $UBUNTU_VERSION main" >> /etc/apt/sources.list.d/xpra.list \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        xpra \
        xpra-html5 \
        xpra-x11 \
    \
    && apt-get remove -y --purge gnupg curl \
    && apt-get autoremove -y --purge \
    \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/xpra

COPY container-entrypoint.sh /container-entrypoint.sh
COPY xpra.conf /etc/xpra/xpra.conf

RUN set -ex \
    \
    && chmod 644 /etc/xpra/ssl-cert.pem \
    && chmod a+r /etc/xpra/xpra.conf \
    && mkdir -p /etc/xdg/menus/ \
    && echo \
"<Menu>\n\
  <Name>Applications</Name>\n\
  <Directory>X-GNOME-Menu-Applications.directory</Directory>\n\
  <DefaultAppDirs/>\n\
  <DefaultDirectoryDirs/>\n\
  <DefaultMergeDirs/>\n\
  <Include>\n\
    <Filename>org.gnome.Software.desktop</Filename>\n\
  </Include>\n\
</Menu>\n" > /etc/xdg/menus/debian-menu.menu \
    && chmod +x "/container-entrypoint.sh"

# Expose Xpra HTML5 client port
EXPOSE 8080

# Use container-entrypoint.sh to allow passing options to Xpra and start Xpra from bash
ENTRYPOINT ["/container-entrypoint.sh"]
