# bind XPRA to all network interfaces on port 10443 for https access
bind-tcp=0.0.0.0:10443
# authenticate using password
tcp-auth=env
# enable HTML5 client
html=on
# enable clipboard
clipboard=yes
clipboard-direction=to-server
# disable printing
printing=no
# disable webcam
webcam=no
# disable MDNS
mdns=no
# disable system notifications and dbus which would be required to deliver them
notifications=no
dbus-proxy=no
dbus-control=no
dbus-launch=no
# disable systemd as it is not available within docker
systemd-run=no
# enable SSL
ssl=yes
# set SSL certificate
ssl-cert=/etc/xpra/ssl/cert.pem
ssl-key=/etc/xpra/ssl/key.pem
# skip certificate verification
ssl-client-verify-mode=none
# Stop service when child is closed
exit-with-children=yes